name: auto_dad_joke
description: A new Flutter project.

version: 1.0.1+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  http: ^0.12.0+2

  sqflite: ^1.1.5
  path: ^1.6.2
  path_provider: ^1.1.0

  animated_stream_list: ^0.0.5

  rxdart: ^0.22.0

  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/
